// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yldgmamvnlffwasoryco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZGdtYW12bmxmZndhc29yeWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDcwMTcsImV4cCI6MjA2NTMyMzAxN30.HylIsK-SzmfGi1cRJ5U5UGR1MfTQ_V4lAetP0i7ldoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);